default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_estudo_development

test:
  <<: *default
  database: ecommerce_estudo_test

production:
  <<: *default
  database: ecommerce_estudo_production
  username: ecommerce_estudo
  password: <%= ENV["ECOMMERCE_ESTUDO_DATABASE_PASSWORD"] %>
